input_type: cartesian
encoder_type: None
attention_type:  relative_bahdanau
batch_size: 1024
embedding_dim:  128
hidden_size: 256
hidden_dim:  256
device : cpu
K: 6
lr: 0.003
mask: True
D: 3
min_freq: 3
num_layers: 1
rate_dropout: 0.5
teacher_force_ratio: 0.5
save_results : h3D_NOsuperv
path : ./models/Interpretable_MC_h3D_f/model_octyrctf

